version: "3.8"

services:
  # Kafka and Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # Databases (one per service)
  user-db:
    image: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  product-db:
    image: postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: product
      POSTGRES_PASSWORD: password

  order-db:
    image: postgres
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password

  # Backend Services
  user-service:
    build: ./user-service  # Builds from user-service/Dockerfile
    ports:
      - "4001:4000"  # Maps host port 4001 to container port 4000
    depends_on:
      - user-db  # Wait for the user-db to start

  product-service:
    build: ./Shopping.ProductService
    ports:
      - "4002:4000"
    depends_on:
      - product-db
      - kafka  # Critical for Kafka communication

  order-service:
    build: ./Shopping.OrderService
    ports:
      - "4003:4000"
    depends_on:
      - order-db
      - kafka  # Must wait for Kafka